apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.monitor.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  brigadeAPIToken: {{ .Values.brigade.apiToken }}
