apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}-github-api-key
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-api-key.pem: |
{{ .Values.github.apiKey | trim | indent 8 }}
