{{- if and .Values.receiver.ingress.enabled .Values.receiver.ingress.tls.enabled (or .Values.receiver.ingress.tls.generateSelfSignedCert .Values.receiver.ingress.tls.cert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.receiver.fullname" . }}-ingress-cert
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.receiver.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.receiver.ingress.tls.generateSelfSignedCert }}
  {{- $cert := genSelfSignedCert .Values.receiver.host nil (list .Values.receiver.host) 3650 }}
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
  {{- else }}
  tls.crt: {{ .Values.receiver.ingress.tls.cert }}
  tls.key: {{ .Values.receiver.ingress.tls.key }}
  {{- end }}
{{- end }}
