apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.receiver.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.receiver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.brigade.apiToken }}
  brigadeAPIToken: {{ .Values.brigade.apiToken }}
  {{- else }}
    {{ fail "Value MUST be specified for brigade.apiToken" }}
  {{- end }}
