apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.receiver.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.receiver.labels" . | nindent 4 }}
type: Opaque
stringData:
  githubAppSharedSecret: {{ .Values.receiver.github.sharedSecret }}
  brigadeAPIToken: {{ .Values.brigade.apiToken }}
