apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.receiver.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.receiver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.receiver.service.type }}
  ports:
  {{- if .Values.receiver.tls.enabled }}
  - port: 443
  {{- else }}
  - port: 80
  {{- end }}
    targetPort: 8080
    {{- if and (eq .Values.receiver.service.type "NodePort") .Values.receiver.service.nodePort}}
    nodePort: {{ .Values.receiver.service.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 8 }}
    {{- include "gateway.receiver.labels" . | nindent 8 }}
